### ISSUE TITLE
eXist-db 3.0.RC2

### ISSUE THREAD

**Issue by welblaud** [eXist-db/xquery-xproc-xmlcalabash-module#3]
I was just about to test XProc in the last dev version:

```
xquery version "3.0";

import module namespace xproc="http://exist-db.org/xproc";

let $simple-xproc as document-node() := document {
    <p:declare-step xmlns:p="http://www.w3.org/ns/xproc" version="1.0">
            <p:input port="source">
                    <p:inline>
                            <doc>Hello world!</doc>
                    </p:inline>
            </p:input>
            <p:output port="result"/>
            <p:identity/>
    </p:declare-step>
}

return
    xproc:process($simple-xproc)
```

It throws:
`Cannot compile xquery: exerr:ERROR error found while loading module xproc: failed to load module: 'http://exist-db.org/xproc' from: 'http://exist-db.org/xproc', location: 'http://exist-db.org/xproc'. Source not found.`

exist.log

```
2016-04-08 12:35:46,786 [eXistThread-26] ERROR (XQueryServlet.java [process]:548) - Cannot compile xquery: exerr:ERROR error found while loading module xproc: f     ailed to load module: 'http://exist-db.org/xproc' from: 'http://exist-db.org/xproc', location: 'http://exist-db.org/xproc'. Source not found.
org.exist.EXistException: Cannot compile xquery: exerr:ERROR error found while loading module xproc: failed to load module: 'http://exist-db.org/xproc' from: 'h     ttp://exist-db.org/xproc', location: 'http://exist-db.org/xproc'. Source not found.
  at org.exist.http.servlets.XQueryServlet.process(XQueryServlet.java:442) [exist-optional.jar:?]
  at org.exist.http.servlets.XQueryServlet.doPost(XQueryServlet.java:197) [exist-optional.jar:?]
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:755) [servlet-api-3.0.jar:?]
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [servlet-api-3.0.jar:?]
  at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575) [jetty-security-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:229) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:103) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.exist.http.urlrewrite.Forward.doRewrite(Forward.java:50) [exist-optional.jar:?]
  at org.exist.http.urlrewrite.XQueryURLRewrite.doRewrite(XQueryURLRewrite.java:549) [exist-optional.jar:?]
  at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:353) [exist-optional.jar:?]
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [servlet-api-3.0.jar:?]
  at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
  at de.betterform.agent.web.filter.XFormsFilter.doFilter(XFormsFilter.java:171) [betterform-exist-5.1-SNAPSHOT-20151014.jar:?]
  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533) [jetty-security-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.server.Server.handle(Server.java:370) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043) [jetty-server-8.1.17.v20150415.jar:8.1.17.v2015041     5]
  at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865) [jetty-http-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240) [jetty-http-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696) [jetty-io-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53) [jetty-io-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [jetty-util-8.1.17.v20150415.jar:8.1.17.v20150415]
  at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [jetty-util-8.1.17.v20150415.jar:8.1.17.v20150415]
  at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
Caused by: org.exist.xquery.XPathException: exerr:ERROR error found while loading module xproc: failed to load module: 'http://exist-db.org/xproc' from: 'http:/     /exist-db.org/xproc', location: 'http://exist-db.org/xproc'. Source not found.
  at org.exist.xquery.XQueryContext.compileModule(XQueryContext.java:2888) ~[exist.jar:?]
  at org.exist.xquery.XQueryContext.compileOrBorrowModule(XQueryContext.java:2857) ~[exist.jar:?]
  at org.exist.xquery.XQueryContext.importModule(XQueryContext.java:2802) ~[exist.jar:?]
  at org.exist.xquery.parser.XQueryTreeParser.importDecl(XQueryTreeParser.java:5663) ~[exist.jar:?]             
```

**Comment by dizzzz** [comment]
I think the required code change hasn't been implemented yet...

**Comment by welblaud** [comment]
Thanks, ok. For me the problem is I can’t use XProc now (in RC1 it is broken too). I have to wait…

**Comment by joewiz** [comment]
The following code, updated only in the module import, works for me using a current build of the project with eXist 4.1.0:

```xquery
xquery version "3.1";

import module namespace xmlcalabash="http://exist-db.org/xquery/xproc/xmlcalabash";

let $simple-xproc as document-node() := document {
    <p:declare-step xmlns:p="http://www.w3.org/ns/xproc" version="1.0">
            <p:input port="source">
                    <p:inline>
                            <doc>Hello world!</doc>
                    </p:inline>
            </p:input>
            <p:output port="result"/>
            <p:identity/>
    </p:declare-step>
}

return
    xmlcalabash:process($simple-xproc)
```

Returns:

```xquery
map {
    "result": "<doc>Hello world!</doc>"
}
```
